### PR TITLE
improve css

### PR DESCRIPTION
**Pull request by TheAwesome98-Real**
improves padding on mobile, may be completely effed on desktop till I next check on there

### CODE REVIEW

**Comment by TheAwesome98-Real** [comment]
wow funny GitHub Pages not letting me contact the api!!!!! I will find out why when I go on my computer (I am writing this pull request from bed

**Comment by TheAwesome98-Real** [comment]
Actually I think the API is down actually since  it happens on prod too

**Comment by lankybox02** [comment]
> Actually I think the API is down actually since it happens on prod too

It was, let me do some local tests on your PR though.

**Comment by lankybox02** [comment]
Pretty sure most browsers display sans-serif font if the requested font isn't installed

**Comment by TheAwesome98-Real** [comment]
> Pretty sure most browsers display sans-serif font if the requested font isn't installed

no they use the serif one

**Comment by lankybox02** [comment]
Conflicting files so i'm just gonna add this manually, thanks for this.

**Comment by TheAwesome98-Real** [comment]
I guess I’ll just deal with the dodgy mobile css :(

**Pull request closed without merging**
